basePath: /
host: localhost:8080
info:
  contact: {}
  description: API server for links
  title: Shortner API
  version: "1.0"
paths:
  /links/{short}:
    delete:
      description: delete line from table filtered by short
      parameters:
      - description: delete link
        in: path
        name: short
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently
          schema:
            type: integer
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: Delete
swagger: "2.0"
